import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, expect, it, vi } from 'vitest'
import { LabelPrintCenter } from './LabelPrintDialog'
import { PreparedProductLabel } from '../../types/barcode.types'
const mocks = vi.hoisted(() => ({ prepare: vi.fn(), search: vi.fn(), print: vi.fn(), pdf: vi.fn(), autoPrint: vi.fn(), replace: vi.fn() }))
vi.mock('../../services/barcode.service', () => ({ prepareProductLabels: mocks.prepare, searchLabelProducts: mocks.search }))
vi.mock('../../components/shared/PrinterSettings', () => ({ default: () => <p>Printer settings</p> }))
vi.mock('jsbarcode', () => ({ default: vi.fn() }))
vi.mock('../../services/printerService', () => ({ printTicketDocument: mocks.print }))
vi.mock('../../services/labelDocument', async original => ({ ...(await original<typeof import('../../services/labelDocument')>()), createLabelPdf: mocks.pdf }))
const product = { _id: 'p1', code: 'P1', name: 'Producto demo', price: 20 }
const label: PreparedProductLabel = { product, barcode: { value: 'FIN123ABC', normalizedValue: 'FIN123ABC', format: 'CODE128', origin: 'INTERNAL', isPrimary: false, unitsPerScan: 1 } }
beforeEach(() => {
  vi.clearAllMocks(); mocks.prepare.mockResolvedValue([label]); mocks.search.mockResolvedValue([product])
  mocks.pdf.mockReturnValue({ autoPrint: mocks.autoPrint, output: () => new Blob(['demo'], { type: 'application/pdf' }) })
  vi.spyOn(window, 'open').mockReturnValue({ opener: null, location: { replace: mocks.replace }, close: vi.fn() } as unknown as Window)
  Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => 'blob:labels') })
  Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() })
})
it('failed refresh clears the previous printable batch and allows explicit recovery', async () => {
  render(<LabelPrintCenter initialProducts={[product]} />)
  const print = screen.getByRole('button', { name: 'Imprimir etiquetas' })
  await waitFor(() => expect((print as HTMLButtonElement).disabled).toBe(false))
  mocks.prepare.mockRejectedValueOnce(new Error('Sin conexión'))
  fireEvent.click(screen.getByRole('button', { name: 'Actualizar códigos y precios' }))
  await screen.findByText('Sin conexión')
  expect((print as HTMLButtonElement).disabled).toBe(true)
  fireEvent.click(print); expect(mocks.print).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Actualizar códigos y precios' }))
  await waitFor(() => expect((print as HTMLButtonElement).disabled).toBe(false))
})
it('uses native PDF printing for labels without QZ, device names or setup', async () => {
  render(<LabelPrintCenter initialProducts={[product]} />)
  const print = screen.getByRole('button', { name: 'Imprimir etiquetas' })
  await waitFor(() => expect((print as HTMLButtonElement).disabled).toBe(false))
  fireEvent.change(screen.getByLabelText('Copias de Producto demo'), { target: { value: '1.5' } })
  expect((print as HTMLButtonElement).disabled).toBe(true)
  fireEvent.change(screen.getByLabelText('Copias de Producto demo'), { target: { value: '2' } })
  fireEvent.click(print)
  expect(mocks.autoPrint).toHaveBeenCalledTimes(1)
  expect(mocks.replace).toHaveBeenCalledWith('blob:labels')
  expect(mocks.print).not.toHaveBeenCalled()
  expect(screen.queryByText(/QZ|Printer settings|Buscar impresoras|Epson|Zebra/)).toBeNull()
  fireEvent.click(print)
  expect(mocks.autoPrint).toHaveBeenCalledTimes(2)
})
it('PDF preview does not request printing and popup blocking is recoverable', async () => {
  render(<LabelPrintCenter initialProducts={[product]} />)
  const preview = screen.getByRole('button', { name: 'Ver PDF' })
  await waitFor(() => expect((preview as HTMLButtonElement).disabled).toBe(false))
  fireEvent.click(preview)
  expect(mocks.autoPrint).not.toHaveBeenCalled()
  vi.spyOn(window, 'open').mockReturnValueOnce(null)
  fireEvent.click(screen.getByRole('button', { name: 'Imprimir etiquetas' }))
  await screen.findByText('Permití abrir una ventana para imprimir las etiquetas.')
  expect(mocks.autoPrint).not.toHaveBeenCalled()
})
it('searches by name, adds the product and removes it from the printable queue', async () => {
  render(<LabelPrintCenter />)
  fireEvent.change(screen.getByLabelText('Buscar productos para etiquetas'), { target: { value: 'demo' } })
  fireEvent.click(screen.getByRole('button', { name: 'Buscar' }))
  fireEvent.click(await screen.findByRole('button', { name: 'Agregar' }))
  await screen.findByLabelText('Copias de Producto demo')
  await waitFor(() => expect(mocks.prepare).toHaveBeenCalledWith(['p1'], 'PRIMARY_OR_INTERNAL'))
  fireEvent.click(screen.getByRole('button', { name: 'Quitar Producto demo' }))
  expect((screen.getByRole('button', { name: 'Imprimir etiquetas' }) as HTMLButtonElement).disabled).toBe(true)
})
